version: "2"
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    ports:
      - 13307:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
